image: "macaronios/phoenix-dev-minimal-devel:latest-amd64"
env:
- LUET_YES=true
- LUET_NOLOCK=true
- HTTP_TIMEOUT=0
prelude:
- >-
  anise repo update --force &&
  anise upgrade &&
  anise i --force
  toolchain/base
  toolchain/base-extra
  toolchain/base-python
  toolchain/base-tools
  toolchain/base-gtk
  toolchain/base-multimedia
  toolchain/base-multimedia2
  toolchain/release
  toolchain/meta-repo
  toolchain/meta-geaaru-kit
  app-admin/whip
  sys-apps/whip-catalog
  macaroni/entities-catalog
  macaroni/ctl
  macaroni/skel-phoenix
  dev-util/pkgs-checker
  app-admin/entities
  system/luet-devkit
  virtual/base
  app-misc/jq
  yq-go
  kernel-5.10/macaroni-lts-sources &&
  anise miner ri virtual/base &&
  anise cleanup --purge-repos &&
  eval 'mkdir /tmp || true' &&
  chmod a+rwx /tmp &&
  eselect kernel set 1 &&
  /usr/bin/gcc-config 1 &&
  source /etc/profile &&
  eselect gcc set 1 &&
  mkdir -p /var/lib/portage &&
  whip hook eclass_db.db_fix_so &&
  whip hook perl.postinst &&
  epro list &&
  eval 'rm /etc/localtime || true' &&
  ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime &&
  macaronictl env-update &&
  eval 'locale-gen || true' &&
  build-docbook-catalog &&
  anise cleanup --purge-repos &&
  entities merge -s /usr/share/macaroni/entities -a &&
  cd / && rm -rf /luetbuild &&
  mkdir /layer

package_dir: /layer
