requires:
- category: "seed"
  name: macaroni-phoenix-base
  version: ">=0"
env:
- FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
prelude:
- >-
  anise rm meta-geaaru-kit -y &&
  cp geaaru-kit /etc/portage/repos.conf/ &&
  mkdir -p /{{ .Values.name }}/ &&
  eval 'emerge --sync || true' &&
  cd /var/git/extra-kits/geaaru-kit &&
  git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*' &&
  git fetch --depth 100 &&
  git checkout {{ ( index .Values.labels "repo_branch" ) }} &&
  git checkout {{ ( index .Values.labels "repo_hash" ) }}
